#!/usr/bin/env python2

import sys
import pipe
import tun
import select
import pipe
import os
import socket
import argparse
import binascii
import subprocess

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--lport', '-l', type=int, default=24601, help='Local port to listen on')
    parser.add_argument('--rport', '-r', type=int, default=24601, help='Remote port to connect to')
    parser.add_argument('--debug', '-d', action='store_true', help='Dump packet I/O')
    parser.add_argument('--cmd', '-c', help='Shell command to execute when link comes up. Environment variable IFACE holds name of interface.')
    parser.add_argument('--compress', '-z', action='store_true', help='Enable data compression (requires python-lzo)')

    parser.add_argument('remote_host', nargs='?', help="Remote host's public address")
    parser.add_argument('key_file', nargs='?', type=argparse.FileType('r'), help="Secret key file")

    parser.add_argument('--make-key', help='Create a new secret key')

    args = parser.parse_args()

    if args.make_key:
        key = pipe.SecretPipe.make_key()
        old_umask = os.umask(0o077)
        with open(args.make_key, 'wb') as fp:
            fp.write(key)
        os.umask(old_umask)
        print "Wrote key to file '%s'. Keep it safe!" % args.make_key
        return

    if not(args.remote_host and args.key_file):
        print "Error: remote_host and key_file must be provided"
        sys.exit(1)

    key = args.key_file.read()
    tap = tun.mktap()

    sp = pipe.SecretPipe(args.lport, args.remote_host, args.rport, key)

    if args.cmd:
        env = dict(os.environ)
        env['IFACE'] = tap.iface
        subprocess.check_call(args.cmd, shell=True, env=env)

    if args.compress:
        from lzo import compress, decompress

    while True:
        r, _, _ = select.select([sp, tap], [], [], 10)

        if sp in r:
            try:
                pkt = sp.recv()
            except socket.error:    # got ICMP Unreachable
                continue

            if not (pkt and len(pkt)):
                continue

            if args.compress:
                pkt = decompress(pkt)

            tap.write(pkt)

            if args.debug:
                print '>', binascii.hexlify(pkt)

        if tap in r:
            pkt = tap.read()

            if args.compress:
                pkt = compress(pkt)

            sp.send(pkt)

            if args.debug:
                print '<', binascii.hexlify(pkt)

        if len(r) == 0:
            # keep hole punch alive
            sp.send("")

if __name__ == "__main__":
    main()
